### PR TITLE
models: cmt: add ADV to cmt prefix

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR fixes the CMT prefixes in the fasm lines accordingly to the prjxray-db update.

### CODE REVIEW

**Review by mkurc-ant — APPROVED** [review]
Ok, LGTM

**Review by litghost — COMMENTED** [review]
Why didn't this get caught in a CI failure?  Do we have no PLL tests right now?

**Comment by acomodi** [comment]
There is an MMCM test here https://github.com/SymbiFlow/symbiflow-xc-fasm2bels/tree/master/tests/test_data/mmcm, but there is a bitstream and no FASM, therefore, with the db update, the fasm features were with the full prefix (`MMCME2_ADV`). I think that is why CI passed.

**Comment by litghost** [comment]
> There is an MMCM test here https://github.com/SymbiFlow/symbiflow-xc-fasm2bels/tree/master/tests/test_data/mmcm, but there is a bitstream and no FASM, therefore, with the db update, the fasm features were with the full prefix (`MMCME2_ADV`). I think that is why CI passed.

Because there is a bitstream there, shouldn't an update of `prjxray-db` data show the failure (because it will then have the new FASM features), and show that the fix worked?

**Comment by acomodi** [comment]
Yeah actually there was a failure when dealing with this PR corresponding to the prjxray-db not being updated: https://github.com/SymbiFlow/symbiflow-xc-fasm2bels/runs/2119727919.

Upon bumping the db, CI went green

**Comment by litghost** [comment]
> Yeah actually there was a failure when dealing with this PR corresponding to the prjxray-db not being updated: https://github.com/SymbiFlow/symbiflow-xc-fasm2bels/runs/2119727919.
> 
> Upon bumping the db, CI went green

Alright, sounds good.  Thanks.

**Pull request merged**
